# models/Local model/base.py
from transformers import AutoTokenizer, AutoModelForCausalLM
from typing import Dict, Any, Optional


class BaseModel:
    def answer(
        self,
        question: str,
        *,
        context: Dict[str, Any],
        metadata: Optional[Dict[str, Any]] = None,
    ) -> str:
        raise NotImplementedError


class LocalModel(BaseModel):
    MODEL_ID = "Qwen/Qwen2.5-Coder-0.5B-Instruct"

    def __init__(self):
        self._tokenizer: Optional[Any] = None
        self._model: Optional[Any] = None
        self._loaded = False

    def _load_model(self) -> None:
        if self._loaded:
            return

        try:
            self._tokenizer = AutoTokenizer.from_pretrained(self.MODEL_ID)
            self._model = AutoModelForCausalLM.from_pretrained(self.MODEL_ID)
            self._loaded = True
        except Exception as e:
            raise RuntimeError(
                f"Failed to load model {self.MODEL_ID}\n\n{e}"
            )

    def answer(
        self,
        question: str,
        *,
        context: Dict[str, Any],
        metadata: Optional[Dict[str, Any]],
    ) -> str:
        try:
            self._load_model()
        except RuntimeError as e:
            return (
                "[LOCAL MODEL ERROR]\n"
                "The local language model could not be loaded.\n\n"
                f"{e}"
            )

        messages = [
            {
                "role": "system",
                "content": (
                    "You are a small local language model running offline. "
                    "Your answers must be short, cautious, and honest. "
                    "If unsure, say you are unsure."
                ),
            },
            {
                "role": "user",
                "content": question,
            },
        ]

        try:
            if self._tokenizer is None or self._model is None:
                raise RuntimeError("Model not loaded properly")
            
            inputs = self._tokenizer.apply_chat_template(
                messages,
                add_generation_prompt=True,
                tokenize=True,
                return_tensors="pt",
                return_dict=True,
            )

            inputs = {k: v.to(self._model.device) for k, v in inputs.items()}

            outputs = self._model.generate(
                **inputs,
                max_new_tokens=128,
                do_sample=True,
                temperature=0.7,
            )

            generated = self._tokenizer.decode(
                outputs[0][inputs["input_ids"].shape[-1]:],
                skip_special_tokens=True,
            )

        except Exception as e:
            return (
                "[LOCAL MODEL ERROR]\n"
                "The local model failed during inference.\n\n"
                f"{e}"
            )

        return (
            "[LOCAL MODEL — LIMITED]\n"
            "This answer was generated by a small offline model "
            "and may be incomplete or inaccurate.\n\n"
            f"{generated.strip()}"
        )